@startuml

title __MESSAGES's Class Diagram__\n

  namespace academy.mindswap.game {
    namespace _factory {
      namespace wheel_of_fortune {
        namespace messages {
          class academy.mindswap.games_factory.wheel_of_fortune.messages.GameMessages {
              {static} + ASK_NAME : String
              {static} + BANKRUPT : String
              {static} + CHOOSE_A_CONSONANT : String
              {static} + CHOOSE_A_VOWEL : String
              {static} + CHOSEN_LETTERS : String
              {static} + FAIL_ANSWER : String
              {static} + FREE_PLAY : String
              {static} + GAME_END : String
              {static} + GUESS_QUOTE : String
              {static} + INVALID_CONSONANT : String
              {static} + INVALID_DOUBLE_CONSONANT : String
              {static} + INVALID_DOUBLE_VOWEL : String
              {static} + INVALID_OPTION : String
              {static} + INVALID_VOWEL : String
              {static} + MISS_TURN : String
              {static} + MONEY_OPTIONS : String
              {static} + NO_MONEY_BUY_VOWEL : String
              {static} + PERMISSION_TO_TALK : String
              {static} + PLAYER_CASH : String
              {static} + PLAYER_CHOOSE_A_CONSONANT : String
              {static} + PLAYER_CHOOSE_A_VOWEL : String
              {static} + PLAYER_CHOOSE_GUESS : String
              {static} + PLAYER_JOINED : String
              {static} + PLAYER_LEFT_GAME : String
              {static} + PLAYER_TURN : String
              {static} + PLAYER_WON : String
              {static} + SPIN_WHEEL : String
              {static} + START_GAME : String
              {static} + THIS_IS_THE_QUOTE : String
              {static} + WAITING_FOR_OTHER_PLAYERS : String
              {static} + WAITING_PLAYER_OPTION : String
              {static} + WELCOME_MESSAGE : String
              {static} + WON_BONUS : String
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
